const KEY='petcare-demo-v1',iso=()=>new Date().toISOString().slice(0,10);
const initial={services:[{id:1,name:'Consulta veterinaria',category:'Atención médica',duration:'45 min',price:85000},{id:2,name:'Vacunación',category:'Prevención',duration:'30 min',price:60000},{id:3,name:'Baño y cuidado',category:'Bienestar',duration:'60 min',price:70000},{id:4,name:'Control posoperatorio',category:'Atención médica',duration:'40 min',price:75000},{id:5,name:'Paseo',category:'Bienestar',duration:'30 min',price:45000}],plans:[{id:'plan-basico',name:'Plan Básico',description:'Servicios básicos de atención y bienestar.',serviceIds:[1,3,5]},{id:'plan-integral',name:'Plan Integral',description:'Servicios de atención, prevención y bienestar.',serviceIds:[1,2,3]},{id:'plan-preventivo',name:'Plan Preventivo',description:'Servicios orientados a prevención y seguimiento.',serviceIds:[2,4]}],pets:[{id:1,name:'Luna',species:'Perro',breed:'Golden retriever',owner:'María Fernanda Ruiz',zone:'Palermo',emoji:'🐕'},{id:2,name:'Milo',species:'Gato',breed:'Criollo',owner:'Andrés Gómez',zone:'Milán',emoji:'🐈'},{id:3,name:'Nala',species:'Perro',breed:'Beagle',owner:'Sofía Ramírez',zone:'Laureles',emoji:'🐶'}],staff:[{id:1,name:'Dra. Valentina López',role:'Médica veterinaria',phone:'300 555 0182',zone:'Centro'},{id:2,name:'Andrés Cárdenas',role:'Auxiliar veterinario',phone:'310 555 0176',zone:'Palermo'},{id:3,name:'Dra. Camila Torres',role:'Médica veterinaria',phone:'312 555 0114',zone:'Milán'}],appointments:[{id:1,petId:1,service:'Consulta veterinaria',date:iso(),time:'09:00',zone:'Palermo',staffId:1,status:'Pendiente'},{id:2,petId:2,service:'Vacunación',date:iso(),time:'10:30',zone:'Milán',staffId:3,status:'Pendiente'},{id:3,petId:3,service:'Baño y cuidado',date:iso(),time:'14:00',zone:'Laureles',staffId:2,status:'Pendiente'}],treatments:[{id:1,petId:1,service:'Vacunación',date:iso(),staffId:1,notes:'Refuerzo anual aplicado.'}],zones:['Centro','Palermo','Milán','Laureles','Chipre','La Enea']};
let db;try{const stored=JSON.parse(localStorage.getItem(KEY));db=stored?{...initial,...stored}:initial}catch{db=initial}let view='inicio';const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),money=n=>new Intl.NumberFormat('es-CO',{style:'currency',currency:'COP',maximumFractionDigits:0}).format(n||0),pet=id=>db.pets.find(x=>x.id===+id)||{name:'Sin mascota',emoji:'🐾',owner:'—',zone:'—'},worker=id=>db.staff.find(x=>x.id===+id)?.name||'Por asignar',date=s=>s?new Date(s+'T12:00:00').toLocaleDateString('es-CO',{day:'2-digit',month:'short',year:'numeric'}):'—',save=()=>localStorage.setItem(KEY,JSON.stringify(db)),planName=id=>db.plans.find(p=>String(p.id)===String(id))?.name||'Sin plan';
function servicesForPlan(planId){const plan=db.plans.find(item=>String(item.id)===String(planId));return db.services.filter(service=>plan?.serviceIds.map(String).includes(String(service.id)))}
function serviceOptionsForPlan(planId){return servicesForPlan(planId).map(service=>`<option value="${esc(service.id)}">${esc(service.name)}</option>`).join('')}
function buildAppointment(values,id){const plan=db.plans.find(item=>String(item.id)===String(values.planId)),service=db.services.find(item=>String(item.id)===String(values.serviceId));if(!plan||!service||!plan.serviceIds.map(String).includes(String(service.id)))return null;const selectedPet=pet(values.petId);return{id,planId:plan.id,serviceId:service.id,service:service.name,petId:+values.petId,date:values.date,time:values.time,zone:values.zone||selectedPet.zone,staffId:+values.staffId||0,status:'Pendiente'}}
function migrateLocalData(){let changed=false;for(const key of ['services','pets','staff','appointments','treatments','zones'])if(!Array.isArray(db[key])){db[key]=initial[key].slice();changed=true}if(!Array.isArray(db.plans)){db.plans=[];changed=true}for(const plan of initial.plans){if(!db.plans.some(existing=>String(existing.id)===String(plan.id))){db.plans.push({...plan,serviceIds:plan.serviceIds.slice()});changed=true}}for(const plan of db.plans)if(!Array.isArray(plan.serviceIds)){plan.serviceIds=[];changed=true}
const paseoName=String(initial.services.find(service=>service.name==='Paseo').name).toLowerCase();let paseo=db.services.find(service=>String(service.name).trim().toLowerCase()===paseoName);if(!paseo){paseo={...initial.services.find(service=>service.name==='Paseo')};if(db.services.some(service=>String(service.id)===String(paseo.id)))paseo.id=Math.max(0,...db.services.map(service=>Number(service.id)||0))+1;db.services.push(paseo);changed=true}
const paseoId=Number(paseo.id),otherServices=db.services.filter(service=>service!==paseo),serviceIdIsValid=Number.isSafeInteger(paseoId)&&paseoId>0&&!otherServices.some(service=>String(service.id)===String(paseo.id));if(!serviceIdIsValid){let nextId=Math.max(0,...db.services.map(service=>Number(service.id)||0))+1;while(db.services.some(service=>String(service.id)===String(nextId)))nextId++;paseo.id=nextId;changed=true}
for(const seed of initial.plans){const plan=db.plans.find(existing=>String(existing.id)===String(seed.id));if(!plan)continue;const present=new Set(plan.serviceIds.map(String));for(const requiredId of seed.serviceIds){const id=seed.id==='plan-basico'&&String(requiredId)==='5'?paseo.id:requiredId;if(!present.has(String(id))){plan.serviceIds.push(id);present.add(String(id));changed=true}}const unique=[],seen=new Set();for(const id of plan.serviceIds){if(!seen.has(String(id))){unique.push(id);seen.add(String(id))}else changed=true}if(unique.length!==plan.serviceIds.length)plan.serviceIds=unique}
for(const appointment of db.appointments)if(!Object.hasOwn(appointment,'planId')){appointment.planId=null;changed=true}if(changed)save()}
migrateLocalData();
const titles={inicio:'Resumen',planes:'Planes y servicios',mascotas:'Mascotas',citas:'Citas',tratamientos:'Tratamientos',personal:'Personal responsable',rutas:'Rutas por zonas'};
function heading(t,d,entity,label){return `<div class="heading"><div><small>PETCARE · MANIZALES</small><h1>${t}</h1><p>${d}</p></div>${entity?`<button class="primary" data-add="${entity}">＋ ${label}</button>`:''}</div>`}function stat(t,n,i){return `<article class="stat"><div>${t}<span>${i}</span></div><strong>${n}</strong><small>Datos de demostración</small></article>`}function toolbar(ph='Buscar…'){return `<div class="toolbar"><input type="search" data-search placeholder="⌕　${ph}"><span data-results></span></div>`}function rows(items){return items.length?items.map(a=>{let p=pet(a.petId);return `<div class="appointment"><b>${esc(a.time)}<small>${date(a.date)}</small></b><span class="pet">${p.emoji}</span><div><b>${esc(p.name)} · ${esc(a.service)}</b><small>${esc(p.owner)} · ${esc(a.zone)} · ${esc(worker(a.staffId))}</small></div><label>${esc(a.status)}</label></div>`}).join(''):'<p class="empty">Sin registros por mostrar.</p>'}
function table(head,body){return `<article class="card tablewrap"><table><thead><tr>${head.map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${body||`<tr><td colspan="${head.length}">Aún no hay registros.</td></tr>`}</tbody></table></article>`}function tr(cells,id){return `<tr data-row>${cells.map(x=>`<td>${x}</td>`).join('')}${id?`<td><button class="delete" data-delete="${id.split(':')[0]}" data-id="${id.split(':')[1]}">···</button></td>`:''}</tr>`}
function dash(){let today=db.appointments.filter(a=>a.date===iso()),z=db.zones.map(x=>[x,db.appointments.filter(a=>a.zone===x&&a.status==='Pendiente').length]).filter(x=>x[1]).sort((a,b)=>b[1]-a[1]);return `${heading('Buenos días, equipo 👋','Resumen de la operación domiciliaria.','cita','Programar cita')}<div class="stats">${stat('Citas de hoy',today.length,'▦')}${stat('Mascotas registradas',db.pets.length,'♧')}${stat('Servicios disponibles',db.services.length,'▤')}${stat('Personal activo',db.staff.length,'♙')}</div><div class="columns"><article class="card"><div class="cardhead"><div><h2>Agenda de hoy</h2><small>Servicios domiciliarios programados</small></div><button class="link" data-view="citas">Ver agenda →</button></div>${rows(today.sort((a,b)=>a.time.localeCompare(b.time)))}</article><article class="card"><div class="cardhead"><div><h2>Visitas por zona</h2><small>Organización de servicios pendientes</small></div><button class="link" data-view="rutas">Ver zonas →</button></div>${z.slice(0,5).map(([n,c])=>`<div class="zoneline"><b>${esc(n)}</b><span>${c} visita(s)</span><div><i style="width:${Math.min(100,c*30)}%"></i></div></div>`).join('')}<p class="callout">Agrupación por zonas de Manizales. Sin GPS ni navegación en tiempo real.</p></article></div><article class="card shortcuts"><h2>Accesos rápidos</h2><div class="quick"><button data-view="mascotas"><b>♧　Registrar mascota</b><small>Agregar mascota y responsable</small></button><button data-view="planes"><b>▤　Consultar servicios</b><small>Revisar servicios disponibles</small></button><button data-view="tratamientos"><b>＋　Registrar atención</b><small>Documentar un servicio realizado</small></button></div></article>`}
function services(){const planCards=db.plans.map(plan=>{const names=plan.serviceIds.map(id=>db.services.find(service=>String(service.id)===String(id))).filter(Boolean).map(service=>esc(service.name));return `<article class="zonecard"><div><h2>${esc(plan.name)}</h2><small>${esc(plan.description)}</small></div><strong>${names.length}</strong><p>${names.length?names.join(' · '):'Sin servicios asociados'}</p></article>`}).join('');return `${heading('Planes y servicios','Consulta y organiza los servicios disponibles.','servicio','Agregar servicio')}<div class="plans-demo"><h2>Planes de demostración</h2><div class="zones">${planCards}</div></div><div class="stats">${stat('Servicios activos',db.services.length,'▤')}${stat('Categorías',new Set(db.services.map(x=>x.category)).size,'◇')}${stat('Duración promedio',db.services.length?Math.round(db.services.reduce((a,x)=>a+parseInt(x.duration),0)/db.services.length)+' min':'0 min','◷')}${stat('Tarifa promedio',money(db.services.length?db.services.reduce((a,x)=>a+x.price,0)/db.services.length:0),'＄')}</div>${toolbar('Buscar servicio…')}${table(['Servicio','Categoría','Duración','Tarifa referencia','Estado',''],db.services.map(s=>tr([esc(s.name),esc(s.category),esc(s.duration),money(s.price),'<em>Activo</em>'],`services:${s.id}`)).join(''))}<p class="callout">Planes y tarifas de demostración. Las tarifas son ilustrativas y deben validarse antes de cualquier uso real.</p>`}
function pets(){return `${heading('Mascotas','Consulta los registros y sus responsables.','mascota','Nueva mascota')}<div class="stats">${stat('Mascotas registradas',db.pets.length,'♧')}${stat('Perros',db.pets.filter(x=>x.species==='Perro').length,'🐕')}${stat('Gatos',db.pets.filter(x=>x.species==='Gato').length,'🐈')}${stat('Zonas cubiertas',new Set(db.pets.map(x=>x.zone)).size,'⌖')}</div>${toolbar('Buscar mascota o responsable…')}${table(['Mascota','Especie','Raza','Responsable','Zona',''],db.pets.map(p=>tr([`${p.emoji}　${esc(p.name)}`,esc(p.species),esc(p.breed),esc(p.owner),`<em>${esc(p.zone)}</em>`],`pets:${p.id}`)).join(''))}<p class="callout">La información se almacena únicamente en este navegador.</p>`}
function appts(){let list=db.appointments.slice().sort((a,b)=>(a.date+a.time).localeCompare(b.date+b.time));return `${heading('Citas','Programa y consulta servicios domiciliarios.','cita','Programar cita')}<div class="stats">${stat('Citas registradas',list.length,'▦')}${stat('Pendientes',list.filter(a=>a.status==='Pendiente').length,'◷')}${stat('Realizadas',list.filter(a=>a.status==='Realizada').length,'✓')}${stat('Zonas con visitas',new Set(list.map(a=>a.zone)).size,'⌖')}</div>${toolbar('Buscar mascota, plan, servicio o zona…')}${table(['Fecha y hora','Mascota','Plan','Servicio','Responsable','Zona','Estado','Acción'],list.map(a=>tr([date(a.date)+' · '+esc(a.time),esc(pet(a.petId).name),esc(planName(a.planId)),esc(a.service),esc(worker(a.staffId)),esc(a.zone),esc(a.status),a.status==='Pendiente'?`<button class="smallbtn" data-done="${a.id}">Marcar realizada</button>`:'—']).replace('<td colspan=', '<td colspan=').replace('</tbody>', '</tbody>')))}<p class="callout">Las citas anteriores a la selección de planes muestran “Sin plan”. La agenda es demostrativa.</p>`}
function treatments(){return `${heading('Tratamientos y servicios','Registra las atenciones realizadas a cada mascota.','tratamiento','Registrar atención')}<div class="stats">${stat('Atenciones registradas',db.treatments.length,'＋')}${stat('Mascotas atendidas',new Set(db.treatments.map(x=>x.petId)).size,'♧')}${stat('Personal responsable',new Set(db.treatments.map(x=>x.staffId)).size,'♙')}${stat('Citas pendientes',db.appointments.filter(a=>a.status==='Pendiente').length,'◷')}</div>${toolbar('Buscar mascota, servicio o responsable…')}${table(['Fecha','Mascota','Servicio realizado','Responsable','Observaciones'],db.treatments.map(t=>`<tr data-row><td>${date(t.date)}</td><td>${pet(t.petId).emoji} ${esc(pet(t.petId).name)}</td><td>${esc(t.service)}</td><td>${esc(worker(t.staffId))}</td><td>${esc(t.notes||'—')}</td></tr>`).join(''))}<p class="callout">Notas ficticias de demostración; no es historia clínica veterinaria.</p>`}
function staff(){return `${heading('Personal responsable','Identifica a las personas asignadas a los servicios.','personal','Agregar personal')}<div class="stats">${stat('Personas registradas',db.staff.length,'♙')}${stat('Veterinarios',db.staff.filter(x=>x.role.includes('veterin')).length,'✚')}${stat('Auxiliares',db.staff.filter(x=>x.role.includes('Auxiliar')).length,'◇')}${stat('Zonas de referencia',new Set(db.staff.map(x=>x.zone)).size,'⌖')}</div>${toolbar('Buscar nombre o rol…')}${table(['Nombre','Rol','Contacto ejemplo','Zona','Estado',''],db.staff.map(s=>tr([esc(s.name),esc(s.role),esc(s.phone),esc(s.zone),'<em>Activo</em>'],`staff:${s.id}`)).join(''))}<p class="callout">Perfiles ficticios usados para ilustrar la identificación del responsable.</p>`}
function routes(){return `${heading('Rutas por zonas','Organiza visitas domiciliarias según sectores de Manizales.','cita','Programar cita')}<div class="stats">${stat('Zonas definidas',db.zones.length,'⌖')}${stat('Visitas pendientes',db.appointments.filter(a=>a.status==='Pendiente').length,'▦')}${stat('Zonas con visitas',new Set(db.appointments.filter(a=>a.status==='Pendiente').map(a=>a.zone)).size,'◇')}${stat('Ciudad','Manizales','⌂')}</div><div class="zones">${db.zones.map(z=>{let a=db.appointments.filter(x=>x.zone===z&&x.status==='Pendiente');return `<article class="zonecard"><div><h2>${esc(z)}</h2><small>Sector de atención · Manizales</small></div><strong>${String(a.length).padStart(2,'0')}</strong><p>${a.length?a.map(x=>`${esc(x.time)} · ${esc(pet(x.petId).name)} · ${esc(x.service)}`).join('<br>'):'Sin servicios pendientes'}</p></article>`}).join('')}</div><article class="card"><h2>Agenda agrupada por sector</h2>${rows(db.appointments.filter(a=>a.status==='Pendiente').sort((a,b)=>a.zone.localeCompare(b.zone)))}</article><p class="callout"><b>Alcance:</b> organización por zonas y agenda de ejemplo. Sin mapas, geolocalización, GPS, cálculo de trayectos ni tráfico en tiempo real.</p>`}
function render(){let fn={inicio:dash,planes:services,mascotas:pets,citas:appts,tratamientos:treatments,personal:staff,rutas:routes}[view];$('#page').innerHTML=fn();$('#crumb').textContent=titles[view];$('#service-count').textContent=db.services.length;document.querySelectorAll('.nav-link').forEach(b=>b.classList.toggle('active',b.dataset.view===view));document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>go(b.dataset.view));document.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>form(b.dataset.add));document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>{if(confirm('¿Eliminar este registro de demostración?')){let [k,id]=[b.dataset.delete,+b.dataset.id];db[k]=db[k].filter(x=>x.id!==id);save();render()}});document.querySelectorAll('[data-done]').forEach(b=>b.onclick=()=>{let a=db.appointments.find(x=>x.id===+b.dataset.done);a.status='Realizada';save();render();toast('Cita marcada como realizada.')});let s=$('[data-search]');if(s)s.oninput=()=>{let rs=[...document.querySelectorAll('[data-row]')],q=s.value.toLowerCase();rs.forEach(r=>r.hidden=!r.innerText.toLowerCase().includes(q));let out=$('[data-results]');if(out)out.textContent=rs.filter(r=>!r.hidden).length+' resultados'}}
function go(v){view=v;$('#sidebar').classList.remove('open');render()}function toast(t){let el=$('#toast');el.textContent=t;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2400)}
function form(kind){
if((kind==='cita'||kind==='tratamiento')&&(!db.pets.length||!db.services.length||!db.staff.length)){toast('Registra mascotas, servicios y personal antes.');return}
const opt=(items,value,label)=>items.map(item=>`<option value="${value(item)}">${esc(label(item))}</option>`).join('');
const zones=opt(db.zones,x=>x,x=>x),pets=opt(db.pets,x=>x.id,x=>x.name+' · '+x.owner),services=opt(db.services,x=>x.name,x=>x.name),staffs=opt(db.staff,x=>x.id,x=>x.name+' · '+x.role),plans=opt(db.plans,x=>x.id,x=>x.name);
const config={
servicio:['Agregar servicio',`<label class="full">Nombre<input name="name" required></label><label>Categoría<input name="category" required></label><label>Duración<input name="duration" placeholder="30 min"></label><label class="full">Tarifa referencia COP<input name="price" type="number" min="0" value="0"></label>`],
mascota:['Registrar mascota',`<label>Nombre<input name="name" required></label><label>Especie<select name="species"><option>Perro</option><option>Gato</option><option>Otro</option></select></label><label>Raza<input name="breed"></label><label>Responsable<input name="owner" required></label><label class="full">Zona<select name="zone">${zones}</select></label>`],
personal:['Agregar personal',`<label class="full">Nombre<input name="name" required></label><label>Rol<select name="role"><option>Médica veterinaria</option><option>Médico veterinario</option><option>Auxiliar veterinario</option><option>Personal encargado</option></select></label><label>Contacto de ejemplo<input name="phone" placeholder="300 000 0000"></label><label class="full">Zona<select name="zone">${zones}</select></label>`],
cita:['Programar cita',`<label class="full">Plan<select name="planId" id="appointment-plan" required>${plans}</select></label><label class="full">Servicio<select name="serviceId" id="appointment-service" required></select></label><label class="full">Mascota<select name="petId" required>${pets}</select></label><label>Fecha<input type="date" name="date" min="${iso()}" value="${iso()}" required></label><label>Hora<input type="time" name="time" value="09:00" required></label><label>Zona<select name="zone">${zones}</select></label><label>Responsable<select name="staffId"><option value="">Por asignar</option>${staffs}</select></label>`],
tratamiento:['Registrar atención realizada',`<label class="full">Mascota<select name="petId">${pets}</select></label><label class="full">Servicio<select name="service">${services}<option>Otro servicio</option></select></label><label>Fecha<input type="date" name="date" value="${iso()}" required></label><label>Responsable<select name="staffId">${staffs}</select></label><label class="full">Observaciones<textarea name="notes"></textarea></label>`]
};
const [title,fields]=config[kind],back=document.createElement('div');back.className='backdrop';back.innerHTML=`<section class="modal" role="dialog" aria-modal="true"><div class="modalhead"><div><h2>${title}</h2><small>Registro local de demostración</small></div><button type="button" class="close">×</button></div><form><div class="formgrid">${fields}</div><div class="actions"><button type="button" class="secondary close2">Cancelar</button><button class="primary">Guardar registro</button></div></form></section>`;document.body.append(back);
const close=()=>back.remove();$('.close',back).onclick=close;$('.close2',back).onclick=close;back.onclick=e=>{if(e.target===back)close()};
if(kind==='cita'){const planSelect=$('#appointment-plan',back),serviceSelect=$('#appointment-service',back);const updateServices=()=>{const previous=serviceSelect.value;serviceSelect.innerHTML=serviceOptionsForPlan(planSelect.value);if([...serviceSelect.options].some(option=>option.value===previous))serviceSelect.value=previous};planSelect.addEventListener('change',updateServices);updateServices()}
$('form',back).onsubmit=e=>{e.preventDefault();const o=Object.fromEntries(new FormData(e.currentTarget)),id=Date.now();
if(kind==='servicio')db.services.push({id,...o,price:+o.price||0,duration:o.duration||'30 min'});
if(kind==='mascota')db.pets.push({id,...o,breed:o.breed||'No especificada',emoji:o.species==='Gato'?'🐈':o.species==='Perro'?'🐕':'🐾'});
if(kind==='personal')db.staff.push({id,...o,phone:o.phone||'—'});
if(kind==='cita'){const appointment=buildAppointment(o,id);if(!appointment){toast('Selecciona un servicio perteneciente al plan.');return}db.appointments.push(appointment)}
if(kind==='tratamiento'){db.treatments.push({id,...o,petId:+o.petId,staffId:+o.staffId,notes:o.notes||'—'});const appointment=db.appointments.find(item=>item.petId===+o.petId&&item.service===o.service&&item.status==='Pendiente');if(appointment)appointment.status='Realizada'}
save();close();render();toast('Registro guardado en este navegador.')}}
document.querySelectorAll('.nav-link').forEach(b=>b.onclick=()=>go(b.dataset.view));$('#menu').onclick=()=>$('#sidebar').classList.toggle('open');$('#today').textContent=new Date().toLocaleDateString('es-CO',{weekday:'long',day:'numeric',month:'long'});render();


